[package]
name = "###NAME###"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }

[addresses]
Std = "0x1"
self = "0x###ADDRESS###"

