[package]
name = "###NAME###"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "23896f357ed5810744842a528e8060dd1200894b" }

[addresses]
Std = "0x1"
self = "0x###ADDRESS###"

