[workspace]
members = [
    "translator/eth",
    "translator/mv",
    "translator/intrinsic",
    "translator",
    "translator/test_infra",
    "translator/me",
    "cli/e2m",
]

[workspace.dependencies]
#Aptos
aptos = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }
aptos-vm = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }
framework = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }
cached-packages = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }
aptos-aggregator = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }
aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }
aptos-gas = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }
aptos-state-view = { git = "https://github.com/aptos-labs/aptos-core", rev = "23d258d1f2440267f866eeb27f9830be48682af8" }

#MOVE
move-binary-format = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }
move-core-types = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b", features = ["address32"] }
move-bytecode-source-map = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }
dependencies = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }
move-bytecode-verifier = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }
move-disassembler = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }
move-ir-types = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }
move-stdlib = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }
move-vm-runtime = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }
move-vm-types = { git = "https://github.com/move-language/move", rev = "a6e1ffba1dab6b5d9f2804a91cd48e6b928e1b3b" }

#EVM
# @todo
evm = { git = "https://github.com/pontem-network/evm.git", branch = "Keccak256" }
evm-core = { git = "https://github.com/pontem-network/evm.git", branch = "Keccak256" }
primitive-types = { version = "0.11", default-features = false, features = ["rlp"] }


anyhow = "~1.0.65"
log = "0.4"
hex = "0.4"
bcs = "0.1.3"
rand = "0.8.5"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
serde_yaml = ">=0.8.26"
ethabi = "17.2"
lazy_static = "1.4"
regex = "1.6"
itertools = "0.10.3"
tempdir = "0.3.7"