[workspace]
members = [
    "translator/eth",
    "translator/mv",
    "translator/intrinsic",
    "translator",
    "translator/test_infra",
    "cli/e2m",
]

[workspace.dependencies]
#Aptos
aptos = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
aptos-vm = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
framework = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
cached-packages = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
aptos-aggregator = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
aptos-gas = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
aptos-state-view = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }
move-deps = { git = "https://github.com/aptos-labs/aptos-core", rev = "8c59034a6c2076780ca261fc2cdad730a298bbc0" }

#MOVE
move-binary-format = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
move-core-types = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
move-bytecode-source-map = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
dependencies = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
move-bytecode-verifier = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
move-disassembler = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
move-ir-types = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
move-stdlib = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
move-vm-runtime = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }
move-vm-types = { git = "https://github.com/move-language/move", rev = "e61c8d7c5e9c8085ce2602ef9a5ae9b2500dbfa4" }

#EVM
evm = { git = "https://github.com/pontem-network/evm.git", branch = "evm2move" }
evm-core = { git = "https://github.com/pontem-network/evm.git", branch = "evm2move" }
