[package]
name = "eth2move"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"
description = "EVM-bytecode to Move static translator"
repository = "https://github.com/pontem-network/eth2move.git"


[dependencies]
hex = "0.4"
clap = { version = "3.1", features = ["derive"] }

# move:
move-core-types = { git = "https://github.com/move-language/move.git" }
move-binary-format = { git = "https://github.com/move-language/move.git" }
move-compiler = { git = "https://github.com/move-language/move.git" }


[dev-dependencies]
maplit = "1.0"


[build-dependencies]
wax = "0.5"
