[workspace]
members = [
    "translator/eth",
    "translator/mv",
    "translator/intrinsic",
    "translator",
    "translator/test_infra",
    "cli/e2m",
]

[workspace.dependencies]
#Aptos
aptos = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
aptos-vm = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
framework = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
cached-packages = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
aptos-aggregator = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
aptos-gas = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
aptos-state-view = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }
move-deps = { git = "https://github.com/aptos-labs/aptos-core", rev = "efb429a0d04f8ff77445d8fd066f445f6531ab06" }

#MOVE
move-binary-format = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
move-core-types = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc", features = ["address32"] }
move-bytecode-source-map = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
dependencies = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
move-bytecode-verifier = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
move-disassembler = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
move-ir-types = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
move-stdlib = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
move-vm-runtime = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
move-vm-types = { git = "https://github.com/move-language/move", rev = "b71fba7ba74656334db952bcb4031e787d3928bc" }
bcs = "0.1.3"

#EVM
evm = { git = "https://github.com/pontem-network/evm.git", branch = "evm2move" }
evm-core = { git = "https://github.com/pontem-network/evm.git", branch = "evm2move" }
primitive-types = { version = "0.11", default-features = false, features = ["rlp"] }


anyhow = "1.0.58"
log = "0.4"
hex = "0.4"

rand = "0.8.5"
serde = { version = "1.0.138", features = ["derive"] }
serde_json = "1.0.82"
ethabi = "17.2"
lazy_static = "1.4"
regex = "1.6"