[package]
name = "eth2move"
version = "0.1.0"
edition = "2021"
build = "src/build.rs"
description = "EVM-bytecode to Move static translator"
repository = "https://github.com/pontem-network/eth2move.git"


[dependencies]
hex = "0.4"
clap = { version = "3.1", features = ["derive"] }

# move:
move-core-types = { git = "https://github.com/move-language/move.git" }
move-binary-format = { git = "https://github.com/move-language/move.git" }
move-compiler = { git = "https://github.com/move-language/move.git" }
# some support libs:
move-bytecode-source-map = { git = "https://github.com/move-language/move.git" }
move-ir-types = { git = "https://github.com/move-language/move.git" }
move-command-line-common = { git = "https://github.com/move-language/move.git" }
move-symbol-pool = { git = "https://github.com/move-language/move.git" }
# /Users/ak/.cargo/git/checkouts/move-0639dd674f581c30/fc59d4f/language/move-symbol-pool/src/symbol.rs

[dev-dependencies]
maplit = "1.0"


[build-dependencies]
wax = "0.5"
