[package]
name = "intrinsic"
version = "0.1.0"
edition = "2021"

[dependencies]
move-binary-format = {git = "https://github.com/move-language/move", rev = "4bdf8d3e76ffaab5c83eda2fa55dfe136c380675" }
move-core-types = {git = "https://github.com/move-language/move", rev = "4bdf8d3e76ffaab5c83eda2fa55dfe136c380675" , features = ["address32"] }
anyhow = "1.0.62"
enum-iterator = "1.2.0"

[dev-dependencies]
move-bytecode-verifier = {git = "https://github.com/move-language/move", rev = "4bdf8d3e76ffaab5c83eda2fa55dfe136c380675"  }
