[package]
name = "intrinsic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
enum-iterator = "1.2.0"
rand = "0.8.5"

move-binary-format = {git = "https://github.com/move-language/move", rev = "94552a7fd7381b84376f6d7008d1f3110b5eccc5" }
move-core-types = {git = "https://github.com/move-language/move", rev = "94552a7fd7381b84376f6d7008d1f3110b5eccc5" , features = ["address32"] }

[dev-dependencies]
move-bytecode-verifier = {git = "https://github.com/move-language/move", rev = "94552a7fd7381b84376f6d7008d1f3110b5eccc5"  }

[build-dependencies]
anyhow = "1.0.62"

move-binary-format = {git = "https://github.com/move-language/move", rev = "94552a7fd7381b84376f6d7008d1f3110b5eccc5" }
move-core-types = {git = "https://github.com/move-language/move", rev = "94552a7fd7381b84376f6d7008d1f3110b5eccc5" , features = ["address32"] }