[package]
name = "intrinsic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
enum-iterator = "1.2.0"
rand = "0.8.5"

move-binary-format = {git = "https://github.com/move-language/move", rev = "59265662d0a44ba53b09ba3c4b2248efdf08c622" }
move-core-types = {git = "https://github.com/move-language/move", rev = "59265662d0a44ba53b09ba3c4b2248efdf08c622" , features = ["address32"] }

[dev-dependencies]
move-bytecode-verifier = {git = "https://github.com/move-language/move", rev = "59265662d0a44ba53b09ba3c4b2248efdf08c622"  }

[build-dependencies]
anyhow = "1.0.62"

move-binary-format = {git = "https://github.com/move-language/move", rev = "59265662d0a44ba53b09ba3c4b2248efdf08c622" }
move-core-types = {git = "https://github.com/move-language/move", rev = "59265662d0a44ba53b09ba3c4b2248efdf08c622" , features = ["address32"] }