[package]
name = "intrinsic"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.62"
enum-iterator = "1.2.0"
rand = "0.8.5"
lazy_static = "1.4.0"

move-binary-format = { git = "https://github.com/move-language/move", rev = "0155b47808de249f4030e84354fde154a1500a82" }
move-core-types = { git = "https://github.com/move-language/move", rev = "0155b47808de249f4030e84354fde154a1500a82", features = ["address32"] }

[dev-dependencies]
move-bytecode-verifier = { git = "https://github.com/move-language/move", rev = "0155b47808de249f4030e84354fde154a1500a82" }

[build-dependencies]
anyhow = "1.0.62"

move-binary-format = { git = "https://github.com/move-language/move", rev = "0155b47808de249f4030e84354fde154a1500a82" }
move-core-types = { git = "https://github.com/move-language/move", rev = "0155b47808de249f4030e84354fde154a1500a82", features = ["address32"] }