[package]
name = "intrinsic"
version = "0.1.0"
edition = "2021"

[dependencies]
move-binary-format = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c" }
anyhow = "1.0.62"

[dev-dependencies]
move-bytecode-verifier = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }
