[package]
name = "test_infra"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.58"
rand = "0.8.5"
hex = "0.4"
bcs = "0.1.3"
env_logger = "0.9.0"
sha3 = "0.10.1"
base32 = "0.4"
serde = {version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"

move-vm-runtime = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }
move-vm-types = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }
move-core-types = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c" , features = ["address32"] }
move-binary-format = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }
move-stdlib = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }

[dev-dependencies]
mv = {path = "../mv"}
evm = {path = "../evm"}
move-bytecode-source-map = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }
move-ir-types = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }
#
evm_pack = {package = "evm", version = "0.35.0"}
primitive-types = { version = "0.11", default-features = false, features = ["rlp"] }

# for test *.sol
libtest-mimic = "0.4"
regex = "1.6"
log = "0.4"
lazy_static = "1.4"
termion = "1.5.6"

[[test]]
name = "sol"
harness = false
