[package]
name = "test_infra"
version = "0.1.0"
edition = "2021"

[dependencies]

[dev-dependencies]
mv = {path = "../mv"}
eth = {path = "../eth" }
move-bytecode-source-map = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }
move-ir-types = {git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c"  }
#
evm = { git = "https://github.com/pontem-network/evm.git", branch = "evm2move" }
primitive-types = { version = "0.11", default-features = false, features = ["rlp"] }
anyhow = "1.0.58"
rand = "0.8.5"
hex = "0.4"
bcs = "0.1.3"
env_logger = "0.9.0"
sha3 = "0.10.1"
base32 = "0.4"
serde = {version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"
once_cell = "1.13.1"

move-vm-runtime = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7", features = ["testing"]  }
move-vm-types = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7"  }
move-core-types = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7" , features = ["address32"] }
move-binary-format = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7"  }
move-stdlib = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7", features = ["testing"] }

aptos-vm = { git = "https://github.com/aptos-labs/aptos-core", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }
aptos-gas = { git = "https://github.com/aptos-labs/aptos-core", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }
move-deps = { git = "https://github.com/aptos-labs/aptos-core", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }
framework = { git = "https://github.com/aptos-labs/aptos-core", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }
aptos-state-view = { git = "https://github.com/aptos-labs/aptos-core", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }
aptos-crypto = { git = "https://github.com/aptos-labs/aptos-core", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }
aptos-aggregator = { git = "https://github.com/aptos-labs/aptos-core", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }

# for test *.sol
libtest-mimic = "0.4"
regex = "1.6"
log = "0.4"
lazy_static = "1.4"
termion = "1.5.6"

[[test]]
name = "sol"
harness = false
