[package]
name = "eth"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
anyhow = "1.0.58"
serde = {version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"
sha3 = "0.10.1"
itertools = "0.10.3"
uint = "0.9.3"
log = "0.4.17"
# types
lazy_static = "1.4"
regex = "1.6"
