[package]
name = "eth"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
anyhow = "1.0.58"
serde = {version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"
sha3 = "0.10.1"
itertools = "0.10.3"
log = "0.4.17"
# types
lazy_static = "1.4"
regex = "1.6"
evm = { git = "https://github.com/pontem-network/evm.git", branch = "evm2move" }
evm-core = { git = "https://github.com/pontem-network/evm.git", branch = "evm2move" }
primitive-types = { version = "0.11", default-features = false, features = ["rlp"] }
move-core-types = {git = "https://github.com/move-language/move", rev = "4bdf8d3e76ffaab5c83eda2fa55dfe136c380675" , features = ["address32"] }
ethabi = "17.2"
