[package]
name = "e2m"
version = "0.1.0"
edition = "2021"
authors = ["Maxim Vladimirov <maxim@pontem.network>"]
license = "MIT"
keywords = ["solidity", "sol", "move", "translator"]
description = "Converting files solidity abi and bin to move"

[dependencies]
clap = { version = ">=3.2.11", features = ["derive"] }
anyhow = "1.0.58"

move-core-types = { git = "https://github.com/move-language/move.git" }
# local
translator = { path = "../../translator" }
inic_log = { path = "../inic_log" }
