[package]
name = "e2m"
version = "0.0.1"
edition = "2021"
authors = [
    "Maxim Vladimirov <maxim@pontem.network>",
    "Dm. Yakushev <dmitryyakushev@dfinance.co>",
]
license = "MIT"
keywords = ["solidity", "sol", "move", "translator"]
description = "Converting the file solidity (abi + bin or sol) to binary code move"

[dependencies]
clap = { version = "3.2.11", features = ["derive"] }
anyhow = "1.0.58"
log = "0.4"
tempfile = "3.3"
serde_yaml = "0.9.11"

#
move-core-types = { git = "https://github.com/move-language/move", rev = "0155b47808de249f4030e84354fde154a1500a82", features = ["address32"] }

# local
translator = { path = "../../translator" }
test_infra = { path = "../../translator/test_infra" }
eth = { path = "../../translator/eth" }


# @todo
primitive-types = "0.12"

# FEATURE DEPLOY
# It is necessary to monitor the relevance. At the moment, this particular client is working with devnet
# You need to download a working client from https://github.com/aptos-labs/aptos-core/releases
#   test it and find out the commit using "aptos info".

bcs = { version = "0.1.3", optional = true }
sha2 = { version = "0.10.5", optional = true }
hex = { version = "0.4", optional = true }
tokio = { version = "1.21", features = ["full"], optional = true }
serde_json = { version = "1.0.82", optional = true }
ethabi = { version = "17.2", optional = true }
reqwest = { version = "0.11", optional = true }

aptos = { git = "https://github.com/aptos-labs/aptos-core", rev = "6d375306122da45a38eb9a6c95625ce2b7f64cbc", optional = true }
aptos-vm = { git = "https://github.com/aptos-labs/aptos-core", rev = "6d375306122da45a38eb9a6c95625ce2b7f64cbc", optional = true }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core", rev = "6d375306122da45a38eb9a6c95625ce2b7f64cbc", optional = true }
framework = { git = "https://github.com/aptos-labs/aptos-core", rev = "6d375306122da45a38eb9a6c95625ce2b7f64cbc", optional = true }
cached-packages = { git = "https://github.com/aptos-labs/aptos-core", rev = "6d375306122da45a38eb9a6c95625ce2b7f64cbc", optional = true }

move-binary-format = { git = "https://github.com/move-language/move", rev = "0155b47808de249f4030e84354fde154a1500a82", optional = true }

[features]
deploy = [
    "bcs",
    "sha2",
    "hex",
    "ethabi",
    "tokio",
    "serde_json",
    "reqwest",
    "aptos",
    "aptos-vm",
    "aptos-types",
    "framework",
    "cached-packages",
    "move-binary-format",
]
