[package]
name = "e2m"
version = "0.1.0"
edition = "2021"
authors = [
    "Maxim Vladimirov <maxim@pontem.network>",
    "Dm. Yakushev <dmitryyakushev@dfinance.co>",
]
license = "MIT"
keywords = ["solidity", "sol", "move", "translator"]
description = "Converting the file solidity (abi + bin or sol) to binary code move"

[dependencies]
clap = { version = "3.1.8", features = ["derive"] }
anyhow = "1.0.58"
sha2 = { version = "0.10", default-features = false }
base32 = "0.4"
log = "0.4"
env_logger = "0.9.0"
tempfile = "3.3"
tokio = { version = "1.18", features = ["full"] }
serde_json = "1.0.82"
#
move-core-types = { git = "https://github.com/move-language/move", rev = "f3c921433758340cb95075ae9918095878686d3c" , features = ["address32"] }
aptos = { git = "https://github.com/aptos-labs/aptos-core", tag = "aptos-cli-v0.2.3" }
aptos-vm = { git = "https://github.com/aptos-labs/aptos-core", tag = "aptos-cli-v0.2.3" }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core", tag = "aptos-cli-v0.2.3" }
# local
translator = { path = "../../translator" }
