[package]
name = "e2m"
version = "0.0.1"
edition = "2021"
authors = [
    "Maxim Vladimirov <maxim@pontem.network>",
    "Dm. Yakushev <dmitryyakushev@dfinance.co>",
]
license = "MIT"
keywords = ["solidity", "sol", "move", "translator"]
description = "Converting the file solidity (abi + bin or sol) to binary code move"

[dependencies]
clap = { version = "3.2.11", features = ["derive"] }
anyhow = "1.0.58"
log = "0.4"
tempfile = "3.3"
serde_yaml = "0.9.11"

#
move-core-types = { git = "https://github.com/move-language/move", rev = "94552a7fd7381b84376f6d7008d1f3110b5eccc5", features = ["address32"] }

# local
translator = { path = "../../translator" }
test_infra = { path = "../../translator/test_infra" }
eth = { path = "../../translator/eth" }


# FEATURE DEPLOY
# It is necessary to monitor the relevance. At the moment, this particular client is working with devnet
# You need to download a working client from https://github.com/aptos-labs/aptos-core/releases
#   test it and find out the commit using "aptos info".

bcs = { version = "0.1.3", optional = true }
sha2 = { version = "0.10.5", optional = true }
hex = { version = "0.4", optional = true }
tokio = { version = "1.21", features = ["full"], optional = true }
serde_json = { version = "1.0.82", optional = true }
ethabi = { version = "17.2", optional = true }

aptos = { git = "https://github.com/aptos-labs/aptos-core", rev = "2a8f88d78a2d140b60d95a6f91cdd97eaaec8ba9", optional = true }
aptos-vm = { git = "https://github.com/aptos-labs/aptos-core", rev = "2a8f88d78a2d140b60d95a6f91cdd97eaaec8ba9", optional = true }
aptos-types = { git = "https://github.com/aptos-labs/aptos-core", rev = "2a8f88d78a2d140b60d95a6f91cdd97eaaec8ba9", optional = true }
framework = { git = "https://github.com/aptos-labs/aptos-core", rev = "2a8f88d78a2d140b60d95a6f91cdd97eaaec8ba9", optional = true }
cached-packages = { git = "https://github.com/aptos-labs/aptos-core", rev = "2a8f88d78a2d140b60d95a6f91cdd97eaaec8ba9", optional = true }

move-binary-format = { git = "https://github.com/move-language/move", rev = "94552a7fd7381b84376f6d7008d1f3110b5eccc5", optional = true }

[features]
deploy = [
    "bcs",
    "sha2",
    "hex",
    "ethabi",
    "tokio",
    "serde_json",
    "aptos",
    "aptos-vm",
    "aptos-types",
    "framework",
    "cached-packages",
    "move-binary-format",
]
