[package]
name = "mv"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
anyhow = "1.0.58"
serde = {version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"
sha3 = "0.10.1"
itertools = "0.10.3"
uint = "0.9.3"
log = "0.4.17"

# local dependencies
eth = {path = "../eth" }
intrinsic = {path = "../intrinsic" }

# move:
move-core-types = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7" , features = ["address32"] }
move-binary-format = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7" }
move-bytecode-source-map = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7"  }
move-ir-types = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7"  }
move-bytecode-verifier = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7"  }
move-disassembler = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7"  }

[dev-dependencies]
rand = "0.8.5"
test_infra = {path = "../test_infra"}