[package]
name = "mv"
version = "0.1.0"
edition = "2021"

[dependencies]
hex = "0.4"
anyhow = "1.0.58"
serde = {version = "1.0.138", features = ["derive"]}
serde_json = "1.0.82"
sha3 = "0.10.1"
itertools = "0.10.3"
uint = "0.9.3"
log = "0.4.17"
ethabi = "17.2"

# local dependencies
eth = {path = "../eth" }
intrinsic = {path = "../intrinsic" }

# move:
move-core-types = {git = "https://github.com/move-language/move", rev = "0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa" , features = ["address32"] }
move-binary-format = {git = "https://github.com/move-language/move", rev = "0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa" }
move-bytecode-source-map = {git = "https://github.com/move-language/move", rev = "0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa"  }
move-ir-types = {git = "https://github.com/move-language/move", rev = "0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa"  }
move-bytecode-verifier = {git = "https://github.com/move-language/move", rev = "0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa"  }
move-disassembler = {git = "https://github.com/move-language/move", rev = "0fe2e6ce5af811d68b8a995b7da3f4c4ecc485fa"  }

[dev-dependencies]
rand = "0.8.5"
test_infra = {path = "../test_infra"}