[package]
name = "intrinsic"
version = "0.0.1"

[dependencies]
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
self = "0x42"

