[package]
name = "intrinsic"
version = "0.0.0"

[dependencies]
AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework/", rev = "61d0d364b43ac0e911c6dc6969fc9e2a8b3e5d2a" }

[addresses]
self = "0x42"

