[package]
name = "intrinsic"
version = "0.0.1"

[dependencies]
EthMathTypes = { local = "../../external/" }
[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'main'
subdir = 'aptos-move/framework/aptos-framework'

[addresses]
self = "0x42"

test_token_admin = "0x43417434fd869edee76cca2a4d2301e528a1551b1d719b75c350c3c97d15b8b9"
test_account = "0x15"
external = "0x242eb66e8fadeb0aadb7027eb2aa78613f4cf903dcd68a798f04de4d123c135a"
