runs:
  using: composite

  steps:
    - name: Formatting
      run: cargo fmt -- --check
      shell: bash

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        name: Clippy Report
        token: ${{ secrets.GITHUB_TOKEN }}
        failure-mode: warnings
        args: --all --all-targets -- -D warnings
