on:
  workflow_dispatch:
    inputs:
      github_token:
        required: true

runs:
  using: composite

  steps:
    - name: Formatting
      run: cargo fmt -- --check
      shell: bash

    - name: Clippy
      uses: actions-rs/clippy-check@v1
      with:
        name: Clippy Report
        token: ${{ inputs.github_token }}
        failure-mode: warnings
        args: --all --all-targets -- -D warnings
