[package]
name = 'sc_users_native'
version = '1.0.0'
upgrade_policy = "compatible"

[addresses]
sc = "_"

[dependencies]
AptosFramework = { git = 'https://github.com/aptos-labs/aptos-core.git', rev = 'main', subdir = 'aptos-move/framework/aptos-framework' }
UsersNative = { local = "../i_users_native" }


