[package]
name = "translator"
version = "0.1.0"
edition = "2021"

[dependencies]
eth = {path = "eth" }
mv = {path = "mv"}

anyhow = "1.0.58"

# move:
move-core-types = {git = "https://github.com/move-language/move", rev = "4cd47108661a5717486e4e90821a4a10f2710ea7" , features = ["address32"] }
