name: Tests
on:
  push:
    branches:
      - master
      - main

env:
  RUSTUP_MAX_RETRIES: 10
  CARGO_INCREMENTAL: 1
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUNNER_ARCH: x64

jobs:
  tests:
    name: Test
    runs-on: macos-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: ./.github/actions/tests
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RUNNER_OS: ${{ runner.os }}

