name: CI

on:
  push:
    branches:
      - ci_release
    tags:
      - 'v*.*.*'


jobs:
  build_and_release:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install latest nightly
        uses: actions-rs/toolchain@v1
        with:
            toolchain: nightly
            override: true
            components: cargo

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version

      - name: Solc latest version
        uses: pontem-network/get-solc@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Aptos latest version
        uses: pontem-network/get-aptos@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Main build
        uses: actions-rs/cargo@v1
        with:
          command: install
          args: --path cli/e2m --features=deploy

      - name: Archive Release
        uses: thedoctor0/zip-release@main
        with:
          type: 'zip'
          filename: 'Release_v0.0.0.zip'
          path: /target/release/e2m

      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: 'Release_v0.0.0.zip'
          token: ${{ secrets.GITHUB_TOKEN }}
