name: CI

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set env
        run: |
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo "TAG_MESSAGE=$(git tag -l --format='%(contents:subject)'${GITHUB_REF#refs/*/})" >> $GITHUB_ENV
      - name: Test
        run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

  # build-linux-binary:
  #   name: "Build Linux binary"
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Install latest nightly
  #       uses: actions-rs/toolchain@v1
  #       with:
  #           toolchain: nightly
  #           override: true
  #           components: cargo

  #     - name: Solc latest version
  #       uses: pontem-network/get-solc@master
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Aptos latest version
  #       uses: pontem-network/get-aptos@main
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Main build
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: install
  #         args: --path cli/e2m --features=deploy

  #     - uses: vimtor/action-zip@v1
  #       with:
  #         files: target/release/e2m
  #         dest: v0.0.0_linux.zip

  #     - name: Upload Binary
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: cli-builds
  #         path: v*.zip

  # build-os-x-binary:
  #   name: "Build OS X binary"
  #   runs-on: macos-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Install latest nightly
  #       uses: actions-rs/toolchain@v1
  #       with:
  #           toolchain: nightly
  #           override: true
  #           components: cargo

  #     - name: Solc latest version
  #       uses: pontem-network/get-solc@master
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Aptos latest version
  #       uses: pontem-network/get-aptos@main
  #       with:
  #         token: ${{ secrets.GITHUB_TOKEN }}

  #     - name: Main build
  #       uses: actions-rs/cargo@v1
  #       with:
  #         command: install
  #         args: --path cli/e2m --features=deploy

  #     - uses: vimtor/action-zip@v1
  #       with:
  #         files: target/release/e2m
  #         dest: v0.0.0_macOS.zip

  #     - name: Upload Binary
  #       uses: actions/upload-artifact@v3
  #       with:
  #         name: cli-builds
  #         path: v*.zip

  # release-binaries:
  #   name: "Release binaries"
  #   needs:
  #     - build-linux-binary
  #     - build-os-x-binary
  #     # - build-windows-binary
  #   runs-on: ubuntu-latest
  #   permissions:
  #     contents: "write"
  #     pull-requests: "read"
  #   steps:
  #     - name: Download prebuilt binaries
  #       uses: actions/download-artifact@v3
  #       with:
  #         name: cli-builds

  #     - name: Display structure of downloaded files
  #       run: ls -R

  #     - name: Create GitHub Release
  #       uses: "marvinpinto/action-automatic-releases@v1.2.1"
  #       with:
  #         repo_token: "${{ secrets.GITHUB_TOKEN }}"
  #         automatic_release_tag: "${{ github.event.inputs.release_tag }}"
  #         prerelease: false
  #         title: "${{ github.event.inputs.release_title }}"
  #         files: |
  #           v*.zip
