name: Tests
on:
  pull_request:
  push:
    branches:
      - master
      - main

env:
  RUSTUP_MAX_RETRIES: 10
  CARGO_INCREMENTAL: 1
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always

jobs:
  tests:
    name: Test
    runs-on: ${{ matrix.os }}
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        shell: bash

    strategy:
      fail-fast: true
      matrix:
        os:
          - ubuntu-latest
          - macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.solc
            ~/.aptos
          key: ${{ runner.os }}-compile

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt, clippy

      - name: Restore Rust cache
        uses: Swatinem/rust-cache@v1

      - name: Solc latest version
        uses: pontem-network/get-solc@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Aptos latest version
        uses: pontem-network/get-aptos@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Formatting
        run: |
          if [ "$RUNNER_OS" == "Linux" ]; then
            cargo fmt -- --check
          fi
        shell: bash

      - name: Test
        run: cargo test
        shell: bash

      - name: Clippy
        uses: actions-rs/clippy-check@v1
        with:
          name: Clippy Report
          token: ${{ secrets.GITHUB_TOKEN }}
          failure-mode: warnings
