name: Tests on Mac
on:
  pull_request:
  push:
    branches:
      - master
      - main

  workflow_call:
    secrets:
      GITHUB_TOKEN:
        required: true

    runner:
      os:
        required: true

env:
  RUSTUP_MAX_RETRIES: 10
  CARGO_INCREMENTAL: 1
  CARGO_NET_RETRY: 10
  CARGO_TERM_COLOR: always
  RUNNER_ARCH: x64

jobs:
  tests:
    name: Tests on Ubuntu
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'ci skip') && !contains(github.event.head_commit.message, 'skip ci')"

    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install
        uses: ./.github/actions/tests
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          runner_os: ${{ runner.os }}

      - name: Test
        run: RUST_BACKTRACE=1 cargo test --offline
        shell: bash

      - name: Clippy + Fmt
        uses: ./.github/actions/clippyfmt
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
